# Generated by Django 4.2.5 on 2023-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais_origen_id',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
